// Venu — the lead-form submission behind each Nuance Book scenario.
//
// This is the web form the prospective client filled in days before anyone
// called them: the exact thing a PC has on screen when the call connects. It
// gives the rep a name and a rough starting point, and nothing that decides the
// case — the fields are coarse self-reported dropdowns, by design.
//
// Generated once by scripts/generate-leads.ts and committed. Kept separate from
// nuance-scenarios.ts so regenerating the book from lib/nuances.html does not
// wipe it.

export interface Lead {
  firstName: string
  lastName: string
  phone: string
  email: string
  accidentWindow: string
  lawyerHandling: string
  state: string
  injuryOption: string
  atFault: string
  /** Drives which Aura voice plays this caller. */
  voiceGender: 'female' | 'male'
}

export const NUANCE_LEADS: Record<string, Lead> = {
  "n1-2": {
    "firstName": "Ben",
    "lastName": "Okafor",
    "phone": "(614) 527-3891",
    "email": "ben.okafor@mailbox.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "male"
  },
  "n1-7": {
    "firstName": "Felicia",
    "lastName": "Adams",
    "phone": "(562) 847-3219",
    "email": "felicia.adams@mailbox.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "female"
  },
  "n1-3": {
    "firstName": "Sophia",
    "lastName": "Marchetti",
    "phone": "(714) 582-3091",
    "email": "sophia.marchetti@mailbox.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "female"
  },
  "n1-4": {
    "firstName": "Andre",
    "lastName": "Phillips",
    "phone": "(404) 822-5139",
    "email": "andre.phillips@gmail.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "male"
  },
  "n1-6": {
    "firstName": "Jordan",
    "lastName": "Reyes",
    "phone": "(714) 528-3421",
    "email": "jordan.reyes.714@gmail.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "male"
  },
  "n1-8": {
    "firstName": "Marcus",
    "lastName": "Webb",
    "phone": "(423) 568-1947",
    "email": "marcus.webb@outlook.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "Not Sure",
    "voiceGender": "male"
  },
  "n1-1": {
    "firstName": "Maria",
    "lastName": "Lopez",
    "phone": "(714) 562-1889",
    "email": "maria.lopez.1987@gmail.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "female"
  },
  "n1-5": {
    "firstName": "David",
    "lastName": "Chen",
    "phone": "(714) 628-3451",
    "email": "dchen.614@gmail.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "Not Sure",
    "voiceGender": "male"
  },
  "n1-9": {
    "firstName": "Angela",
    "lastName": "Brooks",
    "phone": "(714) 523-8891",
    "email": "angela.brooks.1987@outlook.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "female"
  },
  "n2-1": {
    "firstName": "Renee",
    "lastName": "Castillo",
    "phone": "(602) 847-3219",
    "email": "renee.castillo@emailprovider.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "female"
  },
  "n2-3": {
    "firstName": "Marcus",
    "lastName": "Webb",
    "phone": "(619) 423-8751",
    "email": "marcus.webb1987@gmail.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "Not Sure",
    "voiceGender": "male"
  },
  "n2-5": {
    "firstName": "Denise",
    "lastName": "Okafor",
    "phone": "(714) 528-3492",
    "email": "denise.okafor@emailprovider.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "female"
  },
  "n2-2": {
    "firstName": "Angela",
    "lastName": "Brooks",
    "phone": "(615) 428-3091",
    "email": "angela.brooks82@gmail.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Head Injury",
    "atFault": "No",
    "voiceGender": "female"
  },
  "n3-1": {
    "firstName": "Priya",
    "lastName": "Anand",
    "phone": "(408) 562-3847",
    "email": "priya.anand@mailbox.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "female"
  },
  "n2-4": {
    "firstName": "Harold",
    "lastName": "Webb",
    "phone": "(502) 847-3219",
    "email": "harold.webb.family@gmail.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Hospitalization Required",
    "atFault": "Not Sure",
    "voiceGender": "male"
  },
  "n2-6": {
    "firstName": "Travis",
    "lastName": "Holt",
    "phone": "(615) 428-3942",
    "email": "travis.holt@mailbox.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "male"
  },
  "n3-2": {
    "firstName": "Tyler",
    "lastName": "Brooks",
    "phone": "(503) 247-8914",
    "email": "tyler.brooks.transport@gmail.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "Not Sure",
    "voiceGender": "male"
  },
  "n4-1": {
    "firstName": "Olivia",
    "lastName": "Bennett",
    "phone": "(714) 528-3041",
    "email": "olivia.bennett@mailbox.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "female"
  },
  "n3-5": {
    "firstName": "Connor",
    "lastName": "Ellis",
    "phone": "(503) 647-2891",
    "email": "connor.ellis@outlook.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "Not Sure",
    "voiceGender": "male"
  },
  "n3-3": {
    "firstName": "Nicole",
    "lastName": "Foster",
    "phone": "(714) 528-3941",
    "email": "nicole.foster@outmail.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "Not Sure",
    "voiceGender": "female"
  },
  "n4-4": {
    "firstName": "Janet",
    "lastName": "Forsythe",
    "phone": "(541) 628-4392",
    "email": "janet.forsythe@email.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "female"
  },
  "n4-2": {
    "firstName": "Marcus",
    "lastName": "Webb",
    "phone": "(615) 428-3742",
    "email": "marcus.webb@outlook.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "Not Sure",
    "voiceGender": "male"
  },
  "n4-3": {
    "firstName": "Yolanda",
    "lastName": "Ramirez",
    "phone": "(714) 528-3891",
    "email": "yolanda.ramirez.418@gmail.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "female"
  },
  "n4-5": {
    "firstName": "Robert",
    "lastName": "Diaz",
    "phone": "(623) 445-8921",
    "email": "robert.diaz.az@gmail.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "male"
  },
  "n5-2": {
    "firstName": "Latisha",
    "lastName": "Greene",
    "phone": "(714) 528-3942",
    "email": "latisha.greene@email.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "female"
  },
  "n5-3": {
    "firstName": "Samuel",
    "lastName": "Okoye",
    "phone": "(510) 643-2871",
    "email": "samuel.okoye@mailbox.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "male"
  },
  "n5-4": {
    "firstName": "Whitney",
    "lastName": "Park",
    "phone": "(503) 842-7015",
    "email": "whitney.park@outlook.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "female"
  },
  "n5-1": {
    "firstName": "Kevin",
    "lastName": "Marsh",
    "phone": "(714) 528-3941",
    "email": "kmarsh.driver47@gmail.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "male"
  },
  "n6-1": {
    "firstName": "Sandra",
    "lastName": "Mitchell",
    "phone": "(714) 483-2951",
    "email": "sandra.mitchell.2847@gmail.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Broken Bones",
    "atFault": "Not Sure",
    "voiceGender": "female"
  },
  "n5-5": {
    "firstName": "Greg",
    "lastName": "Halloway",
    "phone": "(714) 882-3491",
    "email": "greg.halloway@email.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "Not Sure",
    "voiceGender": "male"
  },
  "n6-3": {
    "firstName": "Cynthia",
    "lastName": "Park",
    "phone": "(562) 418-9074",
    "email": "cynthia.park@emailpro.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "female"
  },
  "n6-2": {
    "firstName": "Robert",
    "lastName": "Jenkins",
    "phone": "(423) 561-8847",
    "email": "rjenkins.87@outlook.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "male"
  },
  "n6-4": {
    "firstName": "Pauline",
    "lastName": "Esposito",
    "phone": "(916) 543-2871",
    "email": "pauline.esposito@gmail.com",
    "accidentWindow": "Within The Past 12 Months",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "female"
  },
  "n7-1": {
    "firstName": "Linda",
    "lastName": "Park",
    "phone": "(714) 582-4039",
    "email": "linda.park.driver@gmail.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "female"
  },
  "n7-2": {
    "firstName": "Devon",
    "lastName": "Carter",
    "phone": "(615) 423-8901",
    "email": "devon.carter@gmail.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "male"
  },
  "n7-3": {
    "firstName": "Ramona",
    "lastName": "Castillo",
    "phone": "(505) 847-2134",
    "email": "ramona.castillo@mailbox.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "female"
  },
  "n3-4": {
    "firstName": "Connor",
    "lastName": "Ellis",
    "phone": "(503) 847-2194",
    "email": "connor.ellis.communications@gmail.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "Not Sure",
    "voiceGender": "male"
  },
  "n8-1": {
    "firstName": "Theresa",
    "lastName": "Allen",
    "phone": "(503) 445-8921",
    "email": "theresa.allen@mailbox.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "female"
  },
  "n6-5": {
    "firstName": "Pauline",
    "lastName": "Esposito",
    "phone": "(661) 524-3198",
    "email": "pauline.esposito@email.com",
    "accidentWindow": "Within The Past 12 Months",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "female"
  },
  "n8-2": {
    "firstName": "Howard",
    "lastName": "Lee",
    "phone": "(503) 641-2847",
    "email": "hlee.howard@gmail.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "male"
  },
  "n8-3": {
    "firstName": "Patrice",
    "lastName": "Nwosu",
    "phone": "(215) 443-8921",
    "email": "patrice.nwosu@mailbox.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Broken Bones",
    "atFault": "Not Sure",
    "voiceGender": "male"
  },
  "n9-1": {
    "firstName": "Natasha",
    "lastName": "Webb",
    "phone": "(503) 447-2891",
    "email": "natasha.webb@emaildomain.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Broken Bones",
    "atFault": "No",
    "voiceGender": "female"
  },
  "n9-3": {
    "firstName": "Renata",
    "lastName": "Hughes",
    "phone": "(602) 847-5294",
    "email": "renata.hughes@mailbox.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "Not Sure",
    "voiceGender": "female"
  },
  "n8-4": {
    "firstName": "Diane",
    "lastName": "Sutter",
    "phone": "(503) 847-2194",
    "email": "diane.sutter@emailaddress.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "female"
  },
  "n9-5": {
    "firstName": "Courtney",
    "lastName": "Diaz",
    "phone": "(714) 528-3941",
    "email": "courtney.diaz@email.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "female"
  },
  "n9-6": {
    "firstName": "Deborah",
    "lastName": "Ainsley",
    "phone": "(614) 382-5941",
    "email": "deborah.ainsley@mailbox.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "Not Sure",
    "voiceGender": "female"
  },
  "n9-7": {
    "firstName": "Margaret",
    "lastName": "Soto",
    "phone": "(562) 847-3291",
    "email": "margaret.soto@email.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "Not Sure",
    "voiceGender": "female"
  },
  "n9-8": {
    "firstName": "Trevor",
    "lastName": "Pham",
    "phone": "(562) 483-9147",
    "email": "tpham.trevor@gmail.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "male"
  },
  "n9-9": {
    "firstName": "Renata",
    "lastName": "Hughes",
    "phone": "(602) 445-8931",
    "email": "renata.hughes@mailbox.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Broken Bones",
    "atFault": "No",
    "voiceGender": "female"
  },
  "n9-4": {
    "firstName": "Jasmine",
    "lastName": "Reed",
    "phone": "(512) 847-3294",
    "email": "jasmine.reed1992@gmail.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "female"
  },
  "n9-10": {
    "firstName": "Lawrence",
    "lastName": "Pruitt",
    "phone": "(503) 847-2194",
    "email": "lawrence.pruitt@medialinkservices.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "Yes",
    "voiceGender": "male"
  },
  "n9-11": {
    "firstName": "Oscar",
    "lastName": "Mendez",
    "phone": "(714) 558-3924",
    "email": "oscar.mendez.1987@outlook.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "Yes",
    "voiceGender": "male"
  },
  "n9-12": {
    "firstName": "Stephanie",
    "lastName": "Burke",
    "phone": "(503) 627-4182",
    "email": "stephanie.burke.1984@gmail.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "Not Sure",
    "voiceGender": "female"
  },
  "n9-13": {
    "firstName": "Yolanda",
    "lastName": "Ramirez",
    "phone": "(916) 447-2834",
    "email": "yolanda.ramirez.1987@gmail.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "female"
  },
  "n10-1": {
    "firstName": "Anthony",
    "lastName": "Russo",
    "phone": "(661) 847-3129",
    "email": "anthony.russo.2847@gmail.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "male"
  },
  "n10-2": {
    "firstName": "Felix",
    "lastName": "Ortega",
    "phone": "(702) 445-8913",
    "email": "felix.ortega@email.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "male"
  },
  "n10-3": {
    "firstName": "Felix",
    "lastName": "Ortega",
    "phone": "(702) 448-3691",
    "email": "felix.ortega.1988@gmail.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "male"
  },
  "n10-4": {
    "firstName": "Wendy",
    "lastName": "Lau",
    "phone": "(714) 523-4891",
    "email": "wendy.lau@emailprovider.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "female"
  },
  "n10-5": {
    "firstName": "Marcus",
    "lastName": "Webb",
    "phone": "(423) 556-7841",
    "email": "marcus.webb.driver@gmail.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "male"
  },
  "n10-7": {
    "firstName": "Caleb",
    "lastName": "Strand",
    "phone": "(602) 447-8931",
    "email": "caleb.strand@mailbox.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "male"
  },
  "n10-6": {
    "firstName": "Priya",
    "lastName": "Anand",
    "phone": "(408) 723-5491",
    "email": "priya.anand.pa@gmail.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "female"
  },
  "n11-1": {
    "firstName": "Hector",
    "lastName": "Villanueva",
    "phone": "(702) 445-8291",
    "email": "hector.villanueva@emailprovider.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "male"
  },
  "n9-2": {
    "firstName": "Brianna",
    "lastName": "Cole",
    "phone": "(714) 528-3941",
    "email": "brianna.cole@emailinc.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "female"
  },
  "n11-3": {
    "firstName": "Imani",
    "lastName": "Carter",
    "phone": "(404) 562-7189",
    "email": "imani.carter.recovery@gmail.com",
    "accidentWindow": "Within The Past 3 Months",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Surgery Required",
    "atFault": "No",
    "voiceGender": "female"
  },
  "n11-4": {
    "firstName": "Theodore",
    "lastName": "Banks",
    "phone": "(503) 847-2194",
    "email": "theodore.banks@mailbox.com",
    "accidentWindow": "More Than 12 Months Ago",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Hospitalization Required",
    "atFault": "No",
    "voiceGender": "male"
  },
  "n11-2": {
    "firstName": "Gerald",
    "lastName": "Thompson",
    "phone": "(503) 445-8291",
    "email": "gthompson.gerald@outlook.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Broken Bones",
    "atFault": "Yes",
    "voiceGender": "male"
  },
  "n11-5": {
    "firstName": "Renata",
    "lastName": "Cole",
    "phone": "(916) 442-8291",
    "email": "renata.cole@emailbox.com",
    "accidentWindow": "Within The Past 12 Months",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Other",
    "atFault": "No",
    "voiceGender": "female"
  },
  "n11-6": {
    "firstName": "Felicity",
    "lastName": "Cho",
    "phone": "(562) 847-3214",
    "email": "felicity.cho@outlook.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "female"
  },
  "n11-9": {
    "firstName": "Paul",
    "lastName": "Martinez",
    "phone": "(602) 485-3192",
    "email": "paul.martinez47@gmail.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "male"
  },
  "n11-8": {
    "firstName": "Monique",
    "lastName": "Davis",
    "phone": "(718) 442-5831",
    "email": "monique.davis.471@gmail.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Broken Bones",
    "atFault": "No",
    "voiceGender": "female"
  },
  "n12-1": {
    "firstName": "Bethany",
    "lastName": "Frost",
    "phone": "(503) 842-5617",
    "email": "bethany.frost.insurance@gmail.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "female"
  },
  "n12-3": {
    "firstName": "Diane",
    "lastName": "Castillo",
    "phone": "(714) 428-5193",
    "email": "diane.castillo42@outlook.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "female"
  },
  "n12-2": {
    "firstName": "Walter",
    "lastName": "Briggs",
    "phone": "(502) 847-3412",
    "email": "walter.briggs.73@gmail.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "male"
  },
  "n12-5": {
    "firstName": "Roger",
    "lastName": "Aldana",
    "phone": "(702) 448-5129",
    "email": "roger.aldana@mailbox.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "male"
  },
  "n12-4": {
    "firstName": "Yusuf",
    "lastName": "Karim",
    "phone": "(714) 382-5941",
    "email": "yusuf.karim@emailprovider.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "male"
  },
  "n12-6": {
    "firstName": "Denise",
    "lastName": "Parker",
    "phone": "(714) 582-3491",
    "email": "denise.parker.2847@gmail.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "female"
  },
  "n12-7": {
    "firstName": "Christine",
    "lastName": "Pham",
    "phone": "(714) 528-3091",
    "email": "christine.pham.2847@gmail.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "female"
  },
  "n11-7": {
    "firstName": "Anthony",
    "lastName": "Brooks",
    "phone": "(503) 847-2156",
    "email": "anthony.brooks.cycling@gmail.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "male"
  },
  "n12-8": {
    "firstName": "Omar",
    "lastName": "Fadel",
    "phone": "(714) 528-3941",
    "email": "omar.fadel@emailservice.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "Not Sure",
    "voiceGender": "male"
  },
  "n12-9": {
    "firstName": "Marcus",
    "lastName": "Webb",
    "phone": "(503) 847-2194",
    "email": "marcus.webb.89@gmail.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "male"
  },
  "n13-2": {
    "firstName": "Felipe",
    "lastName": "Garza",
    "phone": "(702) 483-5291",
    "email": "felipegarza.1988@yahoo.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Head Injury",
    "atFault": "No",
    "voiceGender": "male"
  },
  "n13-1": {
    "firstName": "Eric",
    "lastName": "Sandoval",
    "phone": "(323) 456-8891",
    "email": "eric.sandoval@mailbox.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "male"
  },
  "n13-3": {
    "firstName": "Tasha",
    "lastName": "Bell",
    "phone": "(510) 847-2934",
    "email": "tasha.bell.ca@gmail.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Broken Bones",
    "atFault": "No",
    "voiceGender": "female"
  },
  "n13-4": {
    "firstName": "Whitney",
    "lastName": "Park",
    "phone": "(510) 842-3691",
    "email": "whitney.park.cp@gmail.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "female"
  },
  "n13-6": {
    "firstName": "Nicole",
    "lastName": "Foster",
    "phone": "(775) 428-3091",
    "email": "nfoster.reno@gmail.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "Not Sure",
    "voiceGender": "female"
  },
  "n13-7": {
    "firstName": "Derrick",
    "lastName": "Banks",
    "phone": "(503) 447-2891",
    "email": "derrick.banks@gmail.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "male"
  },
  "n13-5": {
    "firstName": "Janelle",
    "lastName": "Foster",
    "phone": "(213) 847-5291",
    "email": "janelle.foster.2847@gmail.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "female"
  },
  "n14-1": {
    "firstName": "Priscilla",
    "lastName": "Owens",
    "phone": "(714) 528-3412",
    "email": "priscilla.owens@email.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "female"
  },
  "n14-2": {
    "firstName": "Walter",
    "lastName": "Briggs",
    "phone": "(503) 842-7154",
    "email": "wbriggs.walter@gmail.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "male"
  },
  "n14-3": {
    "firstName": "Greg",
    "lastName": "Halloway",
    "phone": "(503) 847-2194",
    "email": "greg.halloway@emailprovider.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "male"
  },
  "n14-4": {
    "firstName": "Patricia",
    "lastName": "Nguyen",
    "phone": "(714) 328-5194",
    "email": "patricia.nguyen@mailbox.com",
    "accidentWindow": "Within The Past 3 Months",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "female"
  },
  "n14-5": {
    "firstName": "Patricia",
    "lastName": "Nguyen",
    "phone": "(714) 382-5941",
    "email": "pnguyen.patricia@gmail.com",
    "accidentWindow": "Within The Past 12 Months",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "female"
  },
  "n14-7": {
    "firstName": "Jerome",
    "lastName": "Tillman",
    "phone": "(502) 641-3847",
    "email": "jerome.tillman.jt@gmail.com",
    "accidentWindow": "Within The Past 12 Months",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "male"
  },
  "n14-6": {
    "firstName": "Marcus",
    "lastName": "Webb",
    "phone": "(541) 823-4912",
    "email": "marcus.webb.1996@gmail.com",
    "accidentWindow": "Within The Past 3 Months",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "male"
  },
  "n14-9": {
    "firstName": "Sandra",
    "lastName": "Ibarra",
    "phone": "(714) 582-4091",
    "email": "sandra.ibarra.mail@gmail.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "female"
  },
  "n14-8": {
    "firstName": "Imani",
    "lastName": "Carter",
    "phone": "(678) 429-5731",
    "email": "imani.carter@emailbox.com",
    "accidentWindow": "Within The Past 3 Months",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Hospitalization Required",
    "atFault": "No",
    "voiceGender": "female"
  },
  "n15-2": {
    "firstName": "Carol",
    "lastName": "Jennings",
    "phone": "(503) 847-2194",
    "email": "carol.jennings.2847@gmail.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "Not Sure",
    "voiceGender": "female"
  },
  "n15-1": {
    "firstName": "Howard",
    "lastName": "Lee",
    "phone": "(714) 385-2891",
    "email": "hlee.howard42@gmail.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "male"
  },
  "n15-3": {
    "firstName": "Russell",
    "lastName": "Vance",
    "phone": "(503) 847-2191",
    "email": "russell.vance@email.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "Not Sure",
    "voiceGender": "male"
  },
  "n15-4": {
    "firstName": "Brenda",
    "lastName": "Solis",
    "phone": "(623) 445-8921",
    "email": "brenda.solis@email.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "female"
  },
  "n15-5": {
    "firstName": "Marvin",
    "lastName": "Atkins",
    "phone": "(334) 587-2041",
    "email": "marvin.atkins@mailbox.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Head Injury",
    "atFault": "No",
    "voiceGender": "male"
  },
  "n15-7": {
    "firstName": "Sheila",
    "lastName": "Brandt",
    "phone": "(916) 445-2783",
    "email": "sheila.brandt@outlook.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "female"
  },
  "n15-6": {
    "firstName": "Denise",
    "lastName": "Okafor",
    "phone": "(614) 528-3742",
    "email": "denise.okafor@gmail.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "female"
  },
  "n16-2": {
    "firstName": "Renee",
    "lastName": "Foster",
    "phone": "(714) 558-2341",
    "email": "renee.foster@emailprovider.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "female"
  },
  "n16-1": {
    "firstName": "Walter",
    "lastName": "Briggs",
    "phone": "(602) 448-7913",
    "email": "wbriggs.walter@gmail.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Broken Bones",
    "atFault": "No",
    "voiceGender": "male"
  },
  "n16-3": {
    "firstName": "Lorraine",
    "lastName": "Pitts",
    "phone": "(734) 528-9143",
    "email": "lorraine.pitts@emailbox.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "female"
  },
  "n15-8": {
    "firstName": "Donald",
    "lastName": "Pierce",
    "phone": "(702) 483-9127",
    "email": "donald.pierce.nv@gmail.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "male"
  },
  "n16-4": {
    "firstName": "Curtis",
    "lastName": "Naylor",
    "phone": "(719) 482-5613",
    "email": "curtis.naylor.work@gmail.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Broken Bones",
    "atFault": "No",
    "voiceGender": "male"
  },
  "n16-5": {
    "firstName": "Donnie",
    "lastName": "Rourke",
    "phone": "(502) 847-3214",
    "email": "donnie.rourke@email.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Broken Bones",
    "atFault": "No",
    "voiceGender": "male"
  },
  "n16-6": {
    "firstName": "Nadia",
    "lastName": "Petrov",
    "phone": "(503) 847-2291",
    "email": "nadia.petrov84@gmail.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "Not Sure",
    "voiceGender": "female"
  },
  "n16-8": {
    "firstName": "Cassandra",
    "lastName": "Bell",
    "phone": "(714) 528-3941",
    "email": "cassandra.bell@emailprovider.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Other",
    "atFault": "No",
    "voiceGender": "female"
  },
  "n17-2": {
    "firstName": "Marcus",
    "lastName": "Pelletier",
    "phone": "(503) 842-6211",
    "email": "mpelletier.marcus@outlook.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "male"
  },
  "n16-7": {
    "firstName": "Renata",
    "lastName": "Cole",
    "phone": "(626) 482-3751",
    "email": "renata.cole@email.com",
    "accidentWindow": "Within The Past 3 Months",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Surgery Required",
    "atFault": "Not Sure",
    "voiceGender": "female"
  },
  "n17-3": {
    "firstName": "Yolanda",
    "lastName": "Pruett",
    "phone": "(714) 528-3941",
    "email": "yolanda.pruett@email.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Broken Bones",
    "atFault": "No",
    "voiceGender": "female"
  },
  "n17-1": {
    "firstName": "Renee",
    "lastName": "Foster",
    "phone": "(503) 847-2914",
    "email": "renee.foster82@gmail.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Surgery Required",
    "atFault": "No",
    "voiceGender": "female"
  },
  "n17-4": {
    "firstName": "Trevor",
    "lastName": "Hale",
    "phone": "(615) 428-3942",
    "email": "trevor.hale@mailnet.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Head Injury",
    "atFault": "No",
    "voiceGender": "male"
  },
  "n17-5": {
    "firstName": "Eleanor",
    "lastName": "Whitfield",
    "phone": "(503) 847-2241",
    "email": "eleanor.whitfield@outlook.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Broken Bones",
    "atFault": "No",
    "voiceGender": "female"
  },
  "n17-6": {
    "firstName": "Gary",
    "lastName": "Holcomb",
    "phone": "(503) 847-2914",
    "email": "gary.holcomb@email.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "male"
  },
  "n17-7": {
    "firstName": "Desiree",
    "lastName": "Holt",
    "phone": "(512) 847-3291",
    "email": "desiree.holt.dvm@gmail.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Surgery Required",
    "atFault": "Not Sure",
    "voiceGender": "female"
  },
  "n18-4": {
    "firstName": "Desmond",
    "lastName": "Carrow",
    "phone": "(209) 445-8723",
    "email": "desmond.carrow@email.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Broken Bones",
    "atFault": "No",
    "voiceGender": "male"
  },
  "n18-3": {
    "firstName": "Renata",
    "lastName": "Holcomb",
    "phone": "(206) 447-8923",
    "email": "renata.holcomb@outlook.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "WA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "female"
  },
  "n18-1": {
    "firstName": "Marisol",
    "lastName": "Vega",
    "phone": "(702) 555-4189",
    "email": "marisol.vega.nv@gmail.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Head Injury",
    "atFault": "No",
    "voiceGender": "female"
  },
  "n18-2": {
    "firstName": "Brandon",
    "lastName": "Hayes",
    "phone": "(303) 555-2847",
    "email": "brandon.hayes.denver@gmail.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "male"
  },
  "n19-1": {
    "firstName": "Marcus",
    "lastName": "Webb",
    "phone": "(661) 555-4892",
    "email": "marcus.webb@email.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "Not Sure",
    "voiceGender": "male"
  },
  "n19-2": {
    "firstName": "Sandra",
    "lastName": "Okafor",
    "phone": "(404) 521-3847",
    "email": "sandra.okafor@emailprovider.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "Not Sure",
    "voiceGender": "female"
  },
  "n19-3": {
    "firstName": "James",
    "lastName": "Holbrook",
    "phone": "(702) 485-3214",
    "email": "james.holbrook.nv@gmail.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "NV",
    "injuryOption": "Aches And Pains",
    "atFault": "Not Sure",
    "voiceGender": "male"
  },
  "n19-4": {
    "firstName": "Priya",
    "lastName": "Chandrasekaran",
    "phone": "(559) 847-3291",
    "email": "priya.chandrasekaran@email.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Head Injury",
    "atFault": "Not Sure",
    "voiceGender": "female"
  },
  "n19-5": {
    "firstName": "Tomás",
    "lastName": "Guerrero",
    "phone": "(702) 445-8923",
    "email": "tguerrero.tomás@gmail.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "NV",
    "injuryOption": "Head Injury",
    "atFault": "Not Sure",
    "voiceGender": "male"
  },
  "n20-1": {
    "firstName": "Cassandra",
    "lastName": "Bell",
    "phone": "(541) 823-4702",
    "email": "cassandra.bell@email.com",
    "accidentWindow": "Within The Past 3 Months",
    "lawyerHandling": "Yes",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "female"
  },
  "n20-4": {
    "firstName": "Tom",
    "lastName": "Whitfield",
    "phone": "(423) 556-7841",
    "email": "tom.whitfield.84@gmail.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "male"
  },
  "n20-3": {
    "firstName": "Michelle",
    "lastName": "Thomas",
    "phone": "(714) 528-3941",
    "email": "michelle.thomas.1987@gmail.com",
    "accidentWindow": "Within The Past 3 Months",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Hospitalization Required",
    "atFault": "Not Sure",
    "voiceGender": "female"
  },
  "n20-2": {
    "firstName": "Phillip",
    "lastName": "Esposito",
    "phone": "(732) 484-2156",
    "email": "phillip.esposito@gmail.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "male"
  },
  "n20-6": {
    "firstName": "James",
    "lastName": "Reyes",
    "phone": "(702) 548-3214",
    "email": "james.reyes84@gmail.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "male"
  },
  "n20-5": {
    "firstName": "Bridget",
    "lastName": "Halvorsen",
    "phone": "(503) 847-2914",
    "email": "bridget.halvorsen@mailservice.net",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "female"
  },
  "n20-7": {
    "firstName": "Desmond",
    "lastName": "Carrow",
    "phone": "(614) 528-3741",
    "email": "desmond.carrow@mailbox.com",
    "accidentWindow": "Within The Past 30 Days",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "Not Sure",
    "voiceGender": "male"
  },
  "n21-1": {
    "firstName": "James",
    "lastName": "Morrison",
    "phone": "(714) 523-8941",
    "email": "jmorrison.claims@gmail.com",
    "accidentWindow": "Within The Past 3 Months",
    "lawyerHandling": "No",
    "state": "CA",
    "injuryOption": "Aches And Pains",
    "atFault": "No",
    "voiceGender": "male"
  }
}

export function getLead(scenarioId: string): Lead | undefined {
  return NUANCE_LEADS[scenarioId]
}

/**
 * Aura voice for a caller.
 *
 * Chosen by measuring all 40 English Aura-2 voices speaking the same distressed
 * line and ranking by pitch relative to register plus pitch movement — the two
 * things that separate "worn down" from "pleased to be on the phone". Tags lie:
 * andromeda is tagged "casual, expressive" and measures the flattest of any
 * female voice by a wide margin.
 *
 *   andromeda  140Hz, 0.87 semitones of movement   (athena, the old pick: 156Hz / 3.03)
 *   zeus        87Hz, 1.99 semitones               (pluto, the old pick: 109Hz / 2.07)
 *   thalia     the original default, 223Hz / 3.93  — the brightest of all of them
 */
export function voiceFor(scenarioId: string): string {
  return NUANCE_LEADS[scenarioId]?.voiceGender === 'male'
    ? 'aura-2-zeus-en'
    : 'aura-2-andromeda-en'
}
